const { GoogleGenAI } = require("@google/genai");

const apiKey = process.env.GOOGLE_GENAI_API_KEY || process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
if (!apiKey) {
    console.warn("CRITICAL: Google GenAI API Key is missing. Please set GOOGLE_GENAI_API_KEY in your .env file.");
}

const genai = new GoogleGenAI({ 
    apiKey
});

async function generateContent(resume, jobDescription, selfDescription) {
    console.log("AI Service: Starting content generation...");
    
    const prompt = `Act as a Senior Technical Recruiter and Career Coach with expertise at top-tier tech companies (MAANG). 
    Your goal is to provide a helpful interview preparation plan by analyzing a candidate's background against a specific Job Description.
    
    IMPORTANT: Use a natural, human-like voice in your writing. Avoid overly mechanical, robotic, or stereotypical AI phrasing. Write like a real experienced recruiter talking directly and warmly to a candidate. Avoid jargon like "Identity Vector", "Strategic Data", or "Protocol".

    INPUT DATA:
    - CANDIDATE RESUME/CONTENT: ${resume || "No resume provided"}
    - CANDIDATE SELF-DESCRIPTION: ${selfDescription || "No self-description provided"}
    - TARGET JOB DESCRIPTION: ${jobDescription}

    SCORING CRITERIA:
    - Match Score (0-100): Be critical. 100 is an exact match in stack and seniority. 
    - Match Analysis: Briefly explain the reasoning behind the score. Highlight 1-2 major strengths and 1-2 critical misalignments.

    INTERVIEW PREPARATION CONTENT:
    1. Technical Questions: Generate 5 questions that specifically verify and challenge the technical experiences and projects mentioned in the candidate's RESUME. These should test the depth of their actual hands-on work.
       - Intention: Verify if the candidate actually performed the work described.
       - Answer: A high-signal response that demonstrates deep competence.
    2. Behavioral Questions: Generate 5 questions based on the candidate's specific background, focused on how their past experiences align with the company's culture.
    3. Skill Gaps: Identify missing skills and categorize by severity.
    4. Adaptive Preparation Plan: Determine the number of preparation days needed (between 7 and 30) based on the size of the 'Skill Gaps'. If gaps are large, provide a 30-day plan; if small, a 7 or 14-day plan.
       - The JSON 'preparationPlan' array should have exactly the number of days you determine as necessary.
       - Each day must have a clear 'focus' and specific 'tasks'.

    SYSTEM INSTRUCTIONS:
    - Return ONLY a valid JSON object.
    - IMPORTANT: Ensure all backslashes and special characters in strings are properly escaped for JSON compliance.
    - No conversational text or markdown.
    - Use the following schema:
    {
        "matchAnalysis": "string",
        "matchScore": number,
        "technicalQuestions": [
            { "question": "string", "intention": "string", "answer": "string" }
        ],
        "behavioralQuestions": [
            { "question": "string", "intention": "string", "answer": "string" }
        ],
        "skillGaps": [
            { "skill": "string", "severity": "low|medium|high", "recommendation": "string" }
        ],
        "preparationPlan": [
            { "day": number, "focus": "string", "tasks": ["string array"] }
        ]
    }`;

    try {
        const response = await genai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
        });

        console.log("AI Service: Response received successfully.");
        let text = response.text;
        
        // Clean markdown if AI included it anyway
        if (text.includes("```")) {
            text = text.replace(/```json/g, "").replace(/```/g, "").trim();
        }

        // Remove control characters (like unescaped newlines or tabs) that break JSON.parse
        text = text.replace(/[\u0000-\u001F\u007F-\u009F]/g, " ");

        return JSON.parse(text || "{}");
    } catch (error) {
        console.error("AI Service Error:", error.message);
        throw error;
    }
}
async function tailorResume(resume, jobDescription, selfDescription) {
    console.log("AI Service: Starting resume tailoring...");
    
    const prompt = `Act as a Senior Technical Recruiter and Career Coach. 
    Your goal is to edit the candidate's Resume to align with the provided Job Description while remaining truthful to their background.
    
    IMPORTANT: Use a natural, human-like voice. The summary and suggestions should sound like they were written by a professional career coach, not a machine. Avoid any robotic phrasing or overly formal jargon that sounds like it was generated by an AI.

    INPUT DATA:
    - CANDIDATE RESUME/CONTENT: ${resume || "No resume provided"}
    - CANDIDATE SELF-DESCRIPTION: ${selfDescription || "No self-description provided"}
    - TARGET JOB DESCRIPTION: ${jobDescription}

    TASK:
    1. Optimized Bio: Write a professional summary (3-4 sentences) tailored for this job.
    2. Key Skills Alignment: Identify the top 10 skills from the JD and map how the candidate fits them.
    3. Resume Improvements: Suggest specific bullet point changes for their experience section to highlight relevant accomplishments.
    4. LaTeX Code for Overleaf: Provide a complete, ready-to-use LaTeX code block for a clean, modern single-column resume. Use standard packages like 'geometry', 'hyperref', 'enumitem', and 'titlesec'. The layout should be professional.

    SYSTEM INSTRUCTIONS:
    - Return ONLY a valid JSON object.
    - IMPORTANT: Ensure all backslashes (especially in LaTeX code) are double-escaped (e.g., \\\\ instead of \\) to maintain valid JSON string format.
    - No conversational text or markdown.
    - Use the following schema:
    {
        "optimizedSummary": "string",
        "keySkills": [
            { "skill": "string", "alignment": "string" }
        ],
        "suggestedChanges": [
            { "original": "string", "optimized": "string", "reason": "string" }
        ],
        "latexCode": "string"
    }`;

    try {
        const response = await genai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
        });

        console.log("AI Service: Resume tailoring response received.");
        let text = response.text;
        
        if (text.includes("```")) {
            text = text.replace(/```json/g, "").replace(/```/g, "").trim();
        }

        // Remove control characters that break JSON.parse (especially in LaTeX blocks)
        text = text.replace(/[\u0000-\u001F\u007F-\u009F]/g, " ");

        return JSON.parse(text || "{}");
    } catch (error) {
        console.error("AI Service Error (Tailoring):", error.message);
        throw error;
    }
}

module.exports = { generateContent, tailorResume };